// <auto-generated />
using ApiCountries.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace ApiCountries.Migrations
{
    [DbContext(typeof(CountriesContext))]
    [Migration("20211014172220_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

            modelBuilder.Entity("ApiCountries.Models.Country", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<double>("Area")
                        .HasColumnType("double precision");

                    b.Property<string>("Capital")
                        .HasColumnType("text");

                    b.Property<string>("Flag")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Region")
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Area = 163610.0,
                            Capital = "Tunis",
                            Flag = "https://flagcdn.com/tn.svg",
                            Name = "Tunisia",
                            Region = "Africa"
                        },
                        new
                        {
                            ID = 2,
                            Area = 43094.0,
                            Capital = "Copenhagen",
                            Flag = "https://flagcdn.com/dk.svg",
                            Name = "Denmark",
                            Region = "Europe"
                        },
                        new
                        {
                            ID = 3,
                            Area = 756102.0,
                            Capital = "Santiago",
                            Flag = "https://flagcdn.com/cl.svg",
                            Name = "Chile",
                            Region = "Americas"
                        },
                        new
                        {
                            ID = 4,
                            Area = 30.0,
                            Flag = "https://flagcdn.com/mo.svg",
                            Name = "Macau",
                            Region = "Asia"
                        },
                        new
                        {
                            ID = 5,
                            Area = 29743.0,
                            Capital = "Yerevan",
                            Flag = "https://flagcdn.com/am.svg",
                            Name = "Armenia",
                            Region = "Asia"
                        },
                        new
                        {
                            ID = 6,
                            Area = 459.0,
                            Capital = "Ngerulmud",
                            Flag = "https://flagcdn.com/pw.svg",
                            Name = "Palau",
                            Region = "Oceania"
                        },
                        new
                        {
                            ID = 7,
                            Area = 45227.0,
                            Capital = "Tallinn",
                            Flag = "https://flagcdn.com/ee.svg",
                            Name = "Estonia",
                            Region = "Europe"
                        },
                        new
                        {
                            ID = 8,
                            Area = 438317.0,
                            Capital = "Baghdad",
                            Flag = "https://flagcdn.com/iq.svg",
                            Name = "Iraq",
                            Region = "Asia"
                        },
                        new
                        {
                            ID = 9,
                            Area = 36193.0,
                            Capital = "Taipei",
                            Flag = "https://flagcdn.com/tw.svg",
                            Name = "Taiwan",
                            Region = "Asia"
                        },
                        new
                        {
                            ID = 10,
                            Area = 51209.0,
                            Capital = "Sarajevo",
                            Flag = "https://flagcdn.com/ba.svg",
                            Name = "Bosnia and Herzegovina",
                            Region = "Europe"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
